const PIPED_INSTANCES = [
  "https://pipedapi.kavin.rocks",
  "https://pipedapi.leptons.xyz",
  "https://pipedapi.nosebs.ru",
  "https://pipedapi-libre.kavin.rocks",
  "https://piped-api.privacy.com.de",
  "https://pipedapi.adminforge.de",
  "https://api.piped.yt",
  "https://api.piped.private.coffee",
  "https://pipedapi.drgns.space"
];

const INSTANCE_BATCH_SIZE = 3;
const STREAM_TIMEOUT_MS = 5000;
const TRACK_TIMEOUT_MS = 8000;
const MAX_TRACK_BYTES = 2 * 1024 * 1024;
const MAX_TRANSCRIPT_CHARS = 500000;

function isValidVideoId(value) {
  return (
    typeof value === "string" &&
    /^[a-zA-Z0-9_-]{11}$/.test(value)
  );
}

function normalizeLanguage(value) {
  return String(value || "").trim().toLowerCase();
}

function isPrivateIPv4(hostname) {
  if (!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(hostname)) {
    return false;
  }

  const parts = hostname.split(".").map(Number);

  if (
    parts.length !== 4 ||
    parts.some((part) => part < 0 || part > 255)
  ) {
    return true;
  }

  const [a, b] = parts;

  return (
    a === 0 ||
    a === 10 ||
    a === 127 ||
    (a === 169 && b === 254) ||
    (a === 172 && b >= 16 && b <= 31) ||
    (a === 192 && b === 168) ||
    a >= 224
  );
}

function isPrivateIPv6(hostname) {
  const host = hostname
    .replace(/^\[/, "")
    .replace(/\]$/, "")
    .toLowerCase();

  return (
    host === "::1" ||
    host === "::" ||
    host.startsWith("fc") ||
    host.startsWith("fd") ||
    /^fe[89ab]/.test(host)
  );
}

function isSafeRemoteUrl(rawUrl) {
  try {
    const url = new URL(rawUrl);

    if (url.protocol !== "https:") {
      return false;
    }

    const host = url.hostname.toLowerCase();

    if (
      !host ||
      host === "localhost" ||
      host.endsWith(".localhost") ||
      host.endsWith(".local") ||
      host.endsWith(".internal")
    ) {
      return false;
    }

    if (
      isPrivateIPv4(host) ||
      (host.includes(":") && isPrivateIPv6(host))
    ) {
      return false;
    }

    return true;
  } catch {
    return false;
  }
}

async function fetchWithTimeout(
  url,
  timeoutMs,
  options = {},
  externalSignal = null
) {
  const controller = new AbortController();

  const abortFromExternal = () => {
    controller.abort();
  };

  if (externalSignal) {
    if (externalSignal.aborted) {
      controller.abort();
    } else {
      externalSignal.addEventListener(
        "abort",
        abortFromExternal,
        { once: true }
      );
    }
  }

  const timeoutId = setTimeout(
    () => controller.abort(),
    timeoutMs
  );

  try {
    return await fetch(url, {
      ...options,
      cache: "no-store",
      redirect: "follow",
      signal: controller.signal,
      headers: {
        Accept: "*/*",
        ...options.headers
      }
    });
  } finally {
    clearTimeout(timeoutId);

    if (externalSignal) {
      externalSignal.removeEventListener(
        "abort",
        abortFromExternal
      );
    }
  }
}

function trackScore(track) {
  const code = normalizeLanguage(track?.code);
  const name = normalizeLanguage(track?.name);

  let score = 0;

  if (
    code === "ar" ||
    code.startsWith("ar-") ||
    name.includes("arabic") ||
    name.includes("العربية")
  ) {
    score += 100;
  } else if (
    code === "en" ||
    code.startsWith("en-") ||
    name.includes("english")
  ) {
    score += 80;
  } else {
    score += 20;
  }

  const autoGenerated =
    track?.autoGenerated === true ||
    track?.auto_generated === true ||
    name.includes("auto-generated") ||
    name.includes("automatically generated");

  if (!autoGenerated) {
    score += 10;
  }

  if (typeof track?.url === "string" && track.url.trim()) {
    score += 5;
  }

  return score;
}

function pickSubtitleTrack(subtitles) {
  if (!Array.isArray(subtitles) || subtitles.length === 0) {
    return null;
  }

  return [...subtitles]
    .filter((track) => track && typeof track === "object")
    .sort((a, b) => trackScore(b) - trackScore(a))[0] || null;
}

function buildVttUrl(rawUrl) {
  if (
    typeof rawUrl !== "string" ||
    !rawUrl.trim() ||
    !isSafeRemoteUrl(rawUrl)
  ) {
    throw new Error("رابط الترجمة غير صالح أو غير آمن.");
  }

  const url = new URL(rawUrl);
  url.searchParams.set("fmt", "vtt");

  return url.toString();
}

function decodeHtmlEntities(text) {
  return String(text || "")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#(\d+);/g, (_, code) => {
      const value = Number(code);

      return Number.isInteger(value) &&
        value >= 0 &&
        value <= 0x10ffff
        ? String.fromCodePoint(value)
        : "";
    })
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => {
      const value = Number.parseInt(code, 16);

      return Number.isInteger(value) &&
        value >= 0 &&
        value <= 0x10ffff
        ? String.fromCodePoint(value)
        : "";
    });
}

function normalizeCaptionLine(line) {
  return decodeHtmlEntities(line)
    .replace(/<[^>]*>/g, "")
    .replace(/\u200b/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function appendWithOverlap(words, nextWords) {
  if (!nextWords.length) {
    return words;
  }

  if (!words.length) {
    return [...nextWords];
  }

  const maxOverlap = Math.min(
    words.length,
    nextWords.length,
    30
  );

  let overlap = 0;

  for (let size = maxOverlap; size >= 1; size -= 1) {
    let matches = true;

    for (let i = 0; i < size; i += 1) {
      if (
        words[words.length - size + i] !==
        nextWords[i]
      ) {
        matches = false;
        break;
      }
    }

    if (matches) {
      overlap = size;
      break;
    }
  }

  words.push(...nextWords.slice(overlap));
  return words;
}

function cleanVtt(vttText) {
  if (
    typeof vttText !== "string" ||
    !vttText.trim()
  ) {
    return "";
  }

  let outputWords = [];
  let previousLine = "";
  let skipBlock = false;

  const lines = vttText
    .replace(/\r/g, "")
    .split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (!line) {
      skipBlock = false;
      continue;
    }

    if (/^(NOTE|STYLE|REGION)(\s|$)/i.test(line)) {
      skipBlock = true;
      continue;
    }

    if (skipBlock) {
      continue;
    }

    if (/^WEBVTT/i.test(line)) {
      continue;
    }

    if (/^(Kind|Language):/i.test(line)) {
      continue;
    }

    if (/^X-TIMESTAMP-MAP=/i.test(line)) {
      continue;
    }

    if (line.includes("-->")) {
      continue;
    }

    if (/^\d+$/.test(line)) {
      continue;
    }

    const cleaned = normalizeCaptionLine(line);

    if (
      !cleaned ||
      cleaned === previousLine
    ) {
      continue;
    }

    outputWords = appendWithOverlap(
      outputWords,
      cleaned.split(/\s+/)
    );

    previousLine = cleaned;

    if (
      outputWords.join(" ").length >=
      MAX_TRANSCRIPT_CHARS
    ) {
      break;
    }
  }

  return outputWords
    .join(" ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, MAX_TRANSCRIPT_CHARS);
}

async function readTrackText(
  trackUrl,
  signal
) {
  const response = await fetchWithTimeout(
    trackUrl,
    TRACK_TIMEOUT_MS,
    {
      headers: {
        Accept:
          "text/vtt,text/plain;q=0.9,*/*;q=0.5"
      }
    },
    signal
  );

  if (!response.ok) {
    throw new Error(
      `Track HTTP ${response.status}`
    );
  }

  const lengthHeader =
    response.headers.get("content-length");

  if (lengthHeader) {
    const declaredSize = Number(lengthHeader);

    if (
      Number.isFinite(declaredSize) &&
      declaredSize > MAX_TRACK_BYTES
    ) {
      throw new Error(
        "ملف الترجمة أكبر من الحد المسموح."
      );
    }
  }

  const text = await response.text();

  if (
    Buffer.byteLength(text, "utf8") >
    MAX_TRACK_BYTES
  ) {
    throw new Error(
      "ملف الترجمة أكبر من الحد المسموح."
    );
  }

  return text;
}

async function tryInstance(
  instance,
  videoId,
  signal
) {
  let foundSubtitleMetadata = false;

  try {
    const streamResponse =
      await fetchWithTimeout(
        `${instance}/streams/${encodeURIComponent(
          videoId
        )}`,
        STREAM_TIMEOUT_MS,
        {
          headers: {
            Accept: "application/json"
          }
        },
        signal
      );

    if (!streamResponse.ok) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    const data =
      await streamResponse.json();

    const subtitles =
      Array.isArray(data?.subtitles)
        ? data.subtitles
        : [];

    if (!subtitles.length) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    foundSubtitleMetadata = true;

    const track =
      pickSubtitleTrack(subtitles);

    if (!track?.url) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    const trackUrl =
      buildVttUrl(track.url);

    const trackText =
      await readTrackText(
        trackUrl,
        signal
      );

    const transcript =
      cleanVtt(trackText);

    if (!transcript) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    return {
      ok: true,
      foundSubtitleMetadata,
      transcript,
      lang:
        track.name ||
        track.code ||
        "unknown",
      code: track.code || null
    };
  } catch {
    return {
      ok: false,
      foundSubtitleMetadata
    };
  }
}

async function runInstanceBatch(
  instances,
  videoId
) {
  const batchController =
    new AbortController();

  const wrapped = instances.map(
    async (instance) => {
      const result =
        await tryInstance(
          instance,
          videoId,
          batchController.signal
        );

      if (result.ok) {
        return result;
      }

      throw result;
    }
  );

  try {
    const winner =
      await Promise.any(wrapped);

    batchController.abort();

    return {
      success: winner,
      foundSubtitleMetadata: true
    };
  } catch (error) {
    batchController.abort();

    const failures =
      Array.isArray(error?.errors)
        ? error.errors
        : [];

    return {
      success: null,
      foundSubtitleMetadata:
        failures.some(
          (item) =>
            item?.foundSubtitleMetadata
        )
    };
  }
}

export default async function handler(
  req,
  res
) {
  res.setHeader(
    "Cache-Control",
    "no-store"
  );

  if (req.method !== "GET") {
    res.setHeader("Allow", "GET");

    return res.status(405).json({
      error:
        "طريقة الطلب غير مدعومة."
    });
  }

  const { videoId } = req.query;

  if (!isValidVideoId(videoId)) {
    return res.status(400).json({
      error:
        "معرف فيديو YouTube غير صالح."
    });
  }

  let foundSubtitleMetadata = false;

  for (
    let index = 0;
    index < PIPED_INSTANCES.length;
    index += INSTANCE_BATCH_SIZE
  ) {
    const batch =
      PIPED_INSTANCES.slice(
        index,
        index + INSTANCE_BATCH_SIZE
      );

    const result =
      await runInstanceBatch(
        batch,
        videoId
      );

    if (
      result.foundSubtitleMetadata
    ) {
      foundSubtitleMetadata = true;
    }

    if (result.success) {
      return res.status(200).json({
        transcript:
          result.success.transcript,
        lang:
          result.success.lang,
        code:
          result.success.code
      });
    }
  }

  if (foundSubtitleMetadata) {
    return res.status(502).json({
      error:
        "تم العثور على ترجمة، لكن تعذر قراءة ملف النص من الخوادم المتاحة حالياً. حاول مرة أخرى بعد قليل."
    });
  }

  return res.status(404).json({
    error:
      "لا تتوفر ترجمة أو نص مفرغ لهذا الفيديو حالياً."
  });
}

