const PIPED_INSTANCES = [
  "https://pipedapi.kavin.rocks",
  "https://pipedapi.leptons.xyz",
  "https://pipedapi.nosebs.ru",
  "https://pipedapi-libre.kavin.rocks",
  "https://piped-api.privacy.com.de",
  "https://pipedapi.adminforge.de",
  "https://api.piped.yt",
  "https://api.piped.private.coffee",
  "https://pipedapi.drgns.space"
];

const INSTANCE_BATCH_SIZE = 3;
const STREAM_TIMEOUT_MS = 5000;
const TRACK_TIMEOUT_MS = 8000;
const YOUTUBE_PAGE_TIMEOUT_MS = 6000;
const YOUTUBE_LIST_TIMEOUT_MS = 5000;
const MAX_TRACK_BYTES = 2 * 1024 * 1024;
const MAX_PAGE_BYTES = 4 * 1024 * 1024;
const MAX_TRANSCRIPT_CHARS = 500000;

const DIRECT_PROBE_LANGUAGES = [
  "ar",
  "en",
  "fr",
  "es"
];

function isValidVideoId(value) {
  return (
    typeof value === "string" &&
    /^[a-zA-Z0-9_-]{11}$/.test(value)
  );
}

function normalizeLanguage(value) {
  return String(value || "")
    .trim()
    .toLowerCase();
}

function isPrivateIPv4(hostname) {
  if (!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(hostname)) {
    return false;
  }

  const parts = hostname
    .split(".")
    .map(Number);

  if (
    parts.length !== 4 ||
    parts.some(
      (part) =>
        !Number.isInteger(part) ||
        part < 0 ||
        part > 255
    )
  ) {
    return true;
  }

  const [a, b] = parts;

  return (
    a === 0 ||
    a === 10 ||
    a === 127 ||
    (a === 169 && b === 254) ||
    (a === 172 && b >= 16 && b <= 31) ||
    (a === 192 && b === 168) ||
    a >= 224
  );
}

function isPrivateIPv6(hostname) {
  const host = hostname
    .replace(/^\[/, "")
    .replace(/\]$/, "")
    .toLowerCase();

  return (
    host === "::1" ||
    host === "::" ||
    host.startsWith("fc") ||
    host.startsWith("fd") ||
    /^fe[89ab]/.test(host)
  );
}

function isSafeRemoteUrl(rawUrl) {
  try {
    const url = new URL(rawUrl);

    if (url.protocol !== "https:") {
      return false;
    }

    const host =
      url.hostname.toLowerCase();

    if (
      !host ||
      host === "localhost" ||
      host.endsWith(".localhost") ||
      host.endsWith(".local") ||
      host.endsWith(".internal")
    ) {
      return false;
    }

    if (
      isPrivateIPv4(host) ||
      (
        host.includes(":") &&
        isPrivateIPv6(host)
      )
    ) {
      return false;
    }

    return true;
  } catch {
    return false;
  }
}

function isAllowedYouTubeCaptionUrl(rawUrl) {
  try {
    const url = new URL(rawUrl);

    if (url.protocol !== "https:") {
      return false;
    }

    const host =
      url.hostname.toLowerCase();

    return (
      host === "youtube.com" ||
      host === "www.youtube.com" ||
      host === "m.youtube.com" ||
      host === "video.google.com" ||
      host.endsWith(".youtube.com") ||
      host.endsWith(".googlevideo.com")
    );
  } catch {
    return false;
  }
}

async function fetchWithTimeout(
  url,
  timeoutMs,
  options = {},
  externalSignal = null
) {
  const controller =
    new AbortController();

  const abortFromExternal = () => {
    controller.abort();
  };

  if (externalSignal) {
    if (externalSignal.aborted) {
      controller.abort();
    } else {
      externalSignal.addEventListener(
        "abort",
        abortFromExternal,
        { once: true }
      );
    }
  }

  const timeoutId = setTimeout(
    () => controller.abort(),
    timeoutMs
  );

  try {
    return await fetch(url, {
      ...options,
      cache: "no-store",
      redirect: "follow",
      signal: controller.signal,
      headers: {
        Accept: "*/*",
        ...options.headers
      }
    });
  } finally {
    clearTimeout(timeoutId);

    if (externalSignal) {
      externalSignal.removeEventListener(
        "abort",
        abortFromExternal
      );
    }
  }
}

function trackScore(track) {
  const code =
    normalizeLanguage(
      track?.code ||
      track?.languageCode
    );

  const name =
    normalizeLanguage(
      track?.name?.simpleText ||
      track?.name ||
      track?.lang_original ||
      track?.lang_translated
    );

  let score = 0;

  if (
    code === "ar" ||
    code.startsWith("ar-") ||
    name.includes("arabic") ||
    name.includes("العربية")
  ) {
    score += 100;
  } else if (
    code === "en" ||
    code.startsWith("en-") ||
    name.includes("english")
  ) {
    score += 80;
  } else {
    score += 20;
  }

  const autoGenerated =
    track?.autoGenerated === true ||
    track?.auto_generated === true ||
    track?.kind === "asr" ||
    name.includes("auto-generated") ||
    name.includes(
      "automatically generated"
    );

  if (!autoGenerated) {
    score += 10;
  }

  if (
    typeof track?.url === "string" &&
    track.url.trim()
  ) {
    score += 5;
  }

  if (
    typeof track?.baseUrl === "string" &&
    track.baseUrl.trim()
  ) {
    score += 5;
  }

  return score;
}

function pickSubtitleTrack(subtitles) {
  if (
    !Array.isArray(subtitles) ||
    subtitles.length === 0
  ) {
    return null;
  }

  return (
    [...subtitles]
      .filter(
        (track) =>
          track &&
          typeof track === "object"
      )
      .sort(
        (a, b) =>
          trackScore(b) -
          trackScore(a)
      )[0] || null
  );
}

function buildVttUrl(rawUrl) {
  if (
    typeof rawUrl !== "string" ||
    !rawUrl.trim() ||
    !isSafeRemoteUrl(rawUrl)
  ) {
    throw new Error(
      "رابط الترجمة غير صالح أو غير آمن."
    );
  }

  const url = new URL(rawUrl);
  url.searchParams.set(
    "fmt",
    "vtt"
  );

  return url.toString();
}

function decodeHtmlEntities(text) {
  return String(text || "")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(
      /&#39;|&apos;/gi,
      "'"
    )
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(
      /&#(\d+);/g,
      (_, code) => {
        const value =
          Number(code);

        return (
          Number.isInteger(value) &&
          value >= 0 &&
          value <= 0x10ffff
        )
          ? String.fromCodePoint(
              value
            )
          : "";
      }
    )
    .replace(
      /&#x([0-9a-f]+);/gi,
      (_, code) => {
        const value =
          Number.parseInt(
            code,
            16
          );

        return (
          Number.isInteger(value) &&
          value >= 0 &&
          value <= 0x10ffff
        )
          ? String.fromCodePoint(
              value
            )
          : "";
      }
    );
}

function normalizeCaptionLine(line) {
  return decodeHtmlEntities(line)
    .replace(/<[^>]*>/g, "")
    .replace(/\u200b/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function appendWithOverlap(
  words,
  nextWords
) {
  if (!nextWords.length) {
    return words;
  }

  if (!words.length) {
    return [...nextWords];
  }

  const maxOverlap =
    Math.min(
      words.length,
      nextWords.length,
      30
    );

  let overlap = 0;

  for (
    let size = maxOverlap;
    size >= 1;
    size -= 1
  ) {
    let matches = true;

    for (
      let i = 0;
      i < size;
      i += 1
    ) {
      if (
        words[
          words.length -
          size +
          i
        ] !== nextWords[i]
      ) {
        matches = false;
        break;
      }
    }

    if (matches) {
      overlap = size;
      break;
    }
  }

  words.push(
    ...nextWords.slice(overlap)
  );

  return words;
}

function cleanVtt(vttText) {
  if (
    typeof vttText !== "string" ||
    !vttText.trim()
  ) {
    return "";
  }

  let outputWords = [];
  let previousLine = "";
  let skipBlock = false;
  let currentLength = 0;

  const lines = vttText
    .replace(/\r/g, "")
    .split("\n");

  for (const rawLine of lines) {
    const line =
      rawLine.trim();

    if (!line) {
      skipBlock = false;
      continue;
    }

    if (
      /^(NOTE|STYLE|REGION)(\s|$)/i.test(
        line
      )
    ) {
      skipBlock = true;
      continue;
    }

    if (skipBlock) {
      continue;
    }

    if (/^WEBVTT/i.test(line)) {
      continue;
    }

    if (
      /^(Kind|Language):/i.test(
        line
      )
    ) {
      continue;
    }

    if (
      /^X-TIMESTAMP-MAP=/i.test(
        line
      )
    ) {
      continue;
    }

    if (line.includes("-->")) {
      continue;
    }

    if (/^\d+$/.test(line)) {
      continue;
    }

    const cleaned =
      normalizeCaptionLine(
        line
      );

    if (
      !cleaned ||
      cleaned === previousLine
    ) {
      continue;
    }

    const words =
      cleaned.split(/\s+/);

    const before =
      outputWords.length;

    outputWords =
      appendWithOverlap(
        outputWords,
        words
      );

    if (
      outputWords.length >
      before
    ) {
      currentLength +=
        cleaned.length + 1;
    }

    previousLine = cleaned;

    if (
      currentLength >=
      MAX_TRANSCRIPT_CHARS
    ) {
      break;
    }
  }

  return outputWords
    .join(" ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(
      0,
      MAX_TRANSCRIPT_CHARS
    );
}

function cleanJson3(data) {
  const events =
    Array.isArray(data?.events)
      ? data.events
      : [];

  let outputWords = [];
  let currentLength = 0;

  for (const event of events) {
    const segments =
      Array.isArray(event?.segs)
        ? event.segs
        : [];

    const raw = segments
      .map(
        (segment) =>
          segment?.utf8 || ""
      )
      .join("");

    const cleaned =
      normalizeCaptionLine(
        raw
      );

    if (!cleaned) {
      continue;
    }

    outputWords =
      appendWithOverlap(
        outputWords,
        cleaned.split(/\s+/)
      );

    currentLength +=
      cleaned.length + 1;

    if (
      currentLength >=
      MAX_TRANSCRIPT_CHARS
    ) {
      break;
    }
  }

  return outputWords
    .join(" ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(
      0,
      MAX_TRANSCRIPT_CHARS
    );
}

function cleanTimedTextXml(xmlText) {
  if (
    typeof xmlText !== "string" ||
    !xmlText.trim()
  ) {
    return "";
  }

  const pieces = [];
  const regex =
    /<text\b[^>]*>([\s\S]*?)<\/text>/gi;

  let match;

  while (
    (match = regex.exec(xmlText))
  ) {
    const cleaned =
      normalizeCaptionLine(
        match[1]
      );

    if (cleaned) {
      pieces.push(cleaned);
    }

    if (
      pieces.join(" ").length >=
      MAX_TRANSCRIPT_CHARS
    ) {
      break;
    }
  }

  return pieces
    .join(" ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(
      0,
      MAX_TRANSCRIPT_CHARS
    );
}

async function readLimitedText(
  response,
  maxBytes
) {
  const lengthHeader =
    response.headers.get(
      "content-length"
    );

  if (lengthHeader) {
    const declaredSize =
      Number(lengthHeader);

    if (
      Number.isFinite(
        declaredSize
      ) &&
      declaredSize > maxBytes
    ) {
      throw new Error(
        "الاستجابة أكبر من الحد المسموح."
      );
    }
  }

  const text =
    await response.text();

  if (
    Buffer.byteLength(
      text,
      "utf8"
    ) > maxBytes
  ) {
    throw new Error(
      "الاستجابة أكبر من الحد المسموح."
    );
  }

  return text;
}

async function readTrackText(
  trackUrl,
  signal
) {
  const response =
    await fetchWithTimeout(
      trackUrl,
      TRACK_TIMEOUT_MS,
      {
        headers: {
          Accept:
            "text/vtt,text/plain;q=0.9,*/*;q=0.5"
        }
      },
      signal
    );

  if (!response.ok) {
    throw new Error(
      `Track HTTP ${response.status}`
    );
  }

  return readLimitedText(
    response,
    MAX_TRACK_BYTES
  );
}

async function tryInstance(
  instance,
  videoId,
  signal
) {
  let foundSubtitleMetadata =
    false;

  try {
    const streamResponse =
      await fetchWithTimeout(
        `${instance}/streams/${encodeURIComponent(
          videoId
        )}`,
        STREAM_TIMEOUT_MS,
        {
          headers: {
            Accept:
              "application/json"
          }
        },
        signal
      );

    if (!streamResponse.ok) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    const data =
      await streamResponse.json();

    const subtitles =
      Array.isArray(
        data?.subtitles
      )
        ? data.subtitles
        : [];

    if (!subtitles.length) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    foundSubtitleMetadata =
      true;

    const track =
      pickSubtitleTrack(
        subtitles
      );

    if (!track?.url) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    const trackUrl =
      buildVttUrl(
        track.url
      );

    const trackText =
      await readTrackText(
        trackUrl,
        signal
      );

    const transcript =
      cleanVtt(trackText);

    if (!transcript) {
      return {
        ok: false,
        foundSubtitleMetadata
      };
    }

    return {
      ok: true,
      foundSubtitleMetadata,
      transcript,
      lang:
        track.name ||
        track.code ||
        "unknown",
      code:
        track.code || null,
      source: "piped"
    };
  } catch {
    return {
      ok: false,
      foundSubtitleMetadata
    };
  }
}

async function runInstanceBatch(
  instances,
  videoId
) {
  const batchController =
    new AbortController();

  const wrapped =
    instances.map(
      async (instance) => {
        const result =
          await tryInstance(
            instance,
            videoId,
            batchController.signal
          );

        if (result.ok) {
          return result;
        }

        throw result;
      }
    );

  try {
    const winner =
      await Promise.any(
        wrapped
      );

    batchController.abort();

    return {
      success: winner,
      foundSubtitleMetadata:
        true
    };
  } catch (error) {
    batchController.abort();

    const failures =
      Array.isArray(
        error?.errors
      )
        ? error.errors
        : [];

    return {
      success: null,
      foundSubtitleMetadata:
        failures.some(
          (item) =>
            item?.foundSubtitleMetadata
        )
    };
  }
}

function extractBalancedJsonArray(
  text,
  marker
) {
  const markerIndex =
    text.indexOf(marker);

  if (markerIndex < 0) {
    return null;
  }

  const start =
    text.indexOf(
      "[",
      markerIndex +
      marker.length
    );

  if (start < 0) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (
    let index = start;
    index < text.length;
    index += 1
  ) {
    const char =
      text[index];

    if (inString) {
      if (escaped) {
        escaped = false;
        continue;
      }

      if (char === "\\") {
        escaped = true;
        continue;
      }

      if (char === '"') {
        inString = false;
      }

      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === "[") {
      depth += 1;
      continue;
    }

    if (char === "]") {
      depth -= 1;

      if (depth === 0) {
        return text.slice(
          start,
          index + 1
        );
      }
    }
  }

  return null;
}

function getTrackDisplayName(
  track
) {
  if (
    typeof track?.name ===
    "string"
  ) {
    return track.name;
  }

  if (
    typeof track?.name
      ?.simpleText ===
    "string"
  ) {
    return track.name
      .simpleText;
  }

  if (
    Array.isArray(
      track?.name?.runs
    )
  ) {
    const value =
      track.name.runs
        .map(
          (item) =>
            item?.text || ""
        )
        .join("")
        .trim();

    if (value) {
      return value;
    }
  }

  return (
    track?.lang_original ||
    track?.lang_translated ||
    track?.languageCode ||
    track?.code ||
    "unknown"
  );
}

async function getYouTubeTracksFromWatchPage(
  videoId
) {
  const url =
    new URL(
      "https://www.youtube.com/watch"
    );

  url.searchParams.set(
    "v",
    videoId
  );

  url.searchParams.set(
    "hl",
    "en"
  );

  const response =
    await fetchWithTimeout(
      url.toString(),
      YOUTUBE_PAGE_TIMEOUT_MS,
      {
        headers: {
          Accept:
            "text/html,application/xhtml+xml",
          "Accept-Language":
            "en-US,en;q=0.9",
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
        }
      }
    );

  if (!response.ok) {
    return [];
  }

  const html =
    await readLimitedText(
      response,
      MAX_PAGE_BYTES
    );

  const jsonArray =
    extractBalancedJsonArray(
      html,
      '"captionTracks":'
    );

  if (!jsonArray) {
    return [];
  }

  try {
    const tracks =
      JSON.parse(jsonArray);

    return Array.isArray(
      tracks
    )
      ? tracks
      : [];
  } catch {
    return [];
  }
}

function parseXmlAttributes(
  input
) {
  const attrs = {};
  const regex =
    /([a-zA-Z0-9_:-]+)="([^"]*)"/g;

  let match;

  while (
    (match = regex.exec(input))
  ) {
    attrs[match[1]] =
      decodeHtmlEntities(
        match[2]
      );
  }

  return attrs;
}

async function getYouTubeTracksFromTimedTextList(
  videoId
) {
  const url =
    new URL(
      "https://www.youtube.com/api/timedtext"
    );

  url.searchParams.set(
    "type",
    "list"
  );

  url.searchParams.set(
    "v",
    videoId
  );

  const response =
    await fetchWithTimeout(
      url.toString(),
      YOUTUBE_LIST_TIMEOUT_MS,
      {
        headers: {
          Accept:
            "text/xml,application/xml,text/plain;q=0.9,*/*;q=0.5",
          "Accept-Language":
            "en-US,en;q=0.9"
        }
      }
    );

  if (!response.ok) {
    return [];
  }

  const xml =
    await readLimitedText(
      response,
      MAX_TRACK_BYTES
    );

  if (!xml.trim()) {
    return [];
  }

  const tracks = [];
  const regex =
    /<track\b([^>]*)\/?>/gi;

  let match;

  while (
    (match = regex.exec(xml))
  ) {
    const attrs =
      parseXmlAttributes(
        match[1]
      );

    const code =
      attrs.lang_code || "";

    if (!code) {
      continue;
    }

    tracks.push({
      languageCode: code,
      name:
        attrs.lang_original ||
        attrs.lang_translated ||
        code,
      kind:
        attrs.kind || null,
      trackName:
        attrs.name || ""
    });
  }

  return tracks;
}

function buildDirectTimedTextUrl(
  videoId,
  track,
  format = "json3"
) {
  const code =
    track?.languageCode ||
    track?.code ||
    track?.lang_code;

  if (
    typeof code !== "string" ||
    !code.trim()
  ) {
    return null;
  }

  const url =
    new URL(
      "https://www.youtube.com/api/timedtext"
    );

  url.searchParams.set(
    "v",
    videoId
  );

  url.searchParams.set(
    "lang",
    code.trim()
  );

  if (format) {
    url.searchParams.set(
      "fmt",
      format
    );
  }

  const kind =
    track?.kind;

  if (
    typeof kind === "string" &&
    kind.trim()
  ) {
    url.searchParams.set(
      "kind",
      kind.trim()
    );
  }

  const name =
    track?.trackName;

  if (
    typeof name === "string" &&
    name.trim()
  ) {
    url.searchParams.set(
      "name",
      name.trim()
    );
  }

  return url.toString();
}

async function fetchYouTubeCaptionUrl(
  rawUrl
) {
  if (
    !isAllowedYouTubeCaptionUrl(
      rawUrl
    )
  ) {
    return "";
  }

  const jsonUrl =
    new URL(rawUrl);

  jsonUrl.searchParams.set(
    "fmt",
    "json3"
  );

  try {
    const response =
      await fetchWithTimeout(
        jsonUrl.toString(),
        TRACK_TIMEOUT_MS,
        {
          headers: {
            Accept:
              "application/json,text/plain;q=0.9,*/*;q=0.5",
            "Accept-Language":
              "en-US,en;q=0.9"
          }
        }
      );

    if (response.ok) {
      const body =
        await readLimitedText(
          response,
          MAX_TRACK_BYTES
        );

      if (body.trim()) {
        try {
          const data =
            JSON.parse(body);

          const transcript =
            cleanJson3(data);

          if (transcript) {
            return transcript;
          }
        } catch {
          const transcript =
            cleanTimedTextXml(
              body
            );

          if (transcript) {
            return transcript;
          }
        }
      }
    }
  } catch {
    // نجرب VTT في الأسفل.
  }

  try {
    const vttUrl =
      new URL(rawUrl);

    vttUrl.searchParams.set(
      "fmt",
      "vtt"
    );

    const response =
      await fetchWithTimeout(
        vttUrl.toString(),
        TRACK_TIMEOUT_MS,
        {
          headers: {
            Accept:
              "text/vtt,text/plain;q=0.9,*/*;q=0.5",
            "Accept-Language":
              "en-US,en;q=0.9"
          }
        }
      );

    if (!response.ok) {
      return "";
    }

    const body =
      await readLimitedText(
        response,
        MAX_TRACK_BYTES
      );

    return cleanVtt(body);
  } catch {
    return "";
  }
}

async function tryYouTubeTrack(
  videoId,
  track
) {
  try {
    const baseUrl =
      track?.baseUrl;

    let transcript = "";

    if (
      typeof baseUrl ===
        "string" &&
      baseUrl.trim()
    ) {
      transcript =
        await fetchYouTubeCaptionUrl(
          baseUrl
        );
    } else {
      const directUrl =
        buildDirectTimedTextUrl(
          videoId,
          track,
          "json3"
        );

      if (directUrl) {
        transcript =
          await fetchYouTubeCaptionUrl(
            directUrl
          );
      }
    }

    if (!transcript) {
      return null;
    }

    return {
      transcript,
      lang:
        getTrackDisplayName(
          track
        ),
      code:
        track?.languageCode ||
        track?.code ||
        track?.lang_code ||
        null,
      source: "youtube"
    };
  } catch {
    return null;
  }
}

async function tryYouTubeTracks(
  videoId,
  tracks
) {
  if (
    !Array.isArray(tracks) ||
    !tracks.length
  ) {
    return null;
  }

  const ordered =
    [...tracks]
      .filter(
        (track) =>
          track &&
          typeof track ===
            "object"
      )
      .sort(
        (a, b) =>
          trackScore(b) -
          trackScore(a)
      );

  for (const track of ordered) {
    const result =
      await tryYouTubeTrack(
        videoId,
        track
      );

    if (result) {
      return result;
    }
  }

  return null;
}

async function tryDirectLanguageProbes(
  videoId
) {
  for (
    const code of
    DIRECT_PROBE_LANGUAGES
  ) {
    const variants = [
      {
        languageCode: code,
        name: code,
        kind: null
      },
      {
        languageCode: code,
        name: code,
        kind: "asr"
      }
    ];

    for (
      const variant of variants
    ) {
      const result =
        await tryYouTubeTrack(
          videoId,
          variant
        );

      if (result) {
        return result;
      }
    }
  }

  return null;
}

async function tryYouTubeDirect(
  videoId
) {
  try {
    const pageTracks =
      await getYouTubeTracksFromWatchPage(
        videoId
      );

    const pageResult =
      await tryYouTubeTracks(
        videoId,
        pageTracks
      );

    if (pageResult) {
      return {
        success: pageResult,
        foundSubtitleMetadata:
          pageTracks.length > 0
      };
    }

    const listTracks =
      await getYouTubeTracksFromTimedTextList(
        videoId
      );

    const listResult =
      await tryYouTubeTracks(
        videoId,
        listTracks
      );

    if (listResult) {
      return {
        success: listResult,
        foundSubtitleMetadata:
          true
      };
    }

    const probeResult =
      await tryDirectLanguageProbes(
        videoId
      );

    if (probeResult) {
      return {
        success: probeResult,
        foundSubtitleMetadata:
          true
      };
    }

    return {
      success: null,
      foundSubtitleMetadata:
        pageTracks.length > 0 ||
        listTracks.length > 0
    };
  } catch {
    return {
      success: null,
      foundSubtitleMetadata:
        false
    };
  }
}

export default async function handler(
  req,
  res
) {
  res.setHeader(
    "Cache-Control",
    "no-store"
  );

  if (req.method !== "GET") {
    res.setHeader(
      "Allow",
      "GET"
    );

    return res
      .status(405)
      .json({
        error:
          "طريقة الطلب غير مدعومة."
      });
  }

  const { videoId } =
    req.query;

  if (
    !isValidVideoId(
      videoId
    )
  ) {
    return res
      .status(400)
      .json({
        error:
          "معرف فيديو YouTube غير صالح."
      });
  }

  let foundSubtitleMetadata =
    false;

  // المرحلة الأولى:
  // تجربة خوادم Piped العامة.
  for (
    let index = 0;
    index <
    PIPED_INSTANCES.length;
    index +=
    INSTANCE_BATCH_SIZE
  ) {
    const batch =
      PIPED_INSTANCES.slice(
        index,
        index +
        INSTANCE_BATCH_SIZE
      );

    const result =
      await runInstanceBatch(
        batch,
        videoId
      );

    if (
      result.foundSubtitleMetadata
    ) {
      foundSubtitleMetadata =
        true;
    }

    if (result.success) {
      return res
        .status(200)
        .json({
          transcript:
            result.success
              .transcript,
          lang:
            result.success.lang,
          code:
            result.success.code,
          source:
            result.success.source
        });
    }
  }

  // المرحلة الثانية:
  // إذا فشل Piped، نحاول قراءة Captions
  // مباشرة من YouTube بدون مفتاح API.
  const youtubeResult =
    await tryYouTubeDirect(
      videoId
    );

  if (
    youtubeResult
      .foundSubtitleMetadata
  ) {
    foundSubtitleMetadata =
      true;
  }

  if (
    youtubeResult.success
  ) {
    return res
      .status(200)
      .json({
        transcript:
          youtubeResult.success
            .transcript,
        lang:
          youtubeResult.success
            .lang,
        code:
          youtubeResult.success
            .code,
        source:
          youtubeResult.success
            .source
      });
  }

  if (
    foundSubtitleMetadata
  ) {
    return res
      .status(502)
      .json({
        error:
          "تم العثور على مسار ترجمة، لكن تعذر قراءة النص حالياً. حاول مرة أخرى بعد قليل."
      });
  }

  return res
    .status(404)
    .json({
      error:
        "لا توجد ترجمة أو Captions متاحة لهذا الفيديو. إذا كان الفيديو بلا نصوص على YouTube فسيحتاج إلى تحويل الصوت إلى نص."
    });
}

